import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import LenisScroll from "@/components/LenisScroll";
import CustomCursor from "@/components/ui/customCursor";
import localFont from "next/font/local";
import DeviceOverlay from '@/components/ui/deviceOverlay'

export const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});
const generalSans = localFont({
  src: [{ path: "../public/fonts/GeneralSans-Variable.ttf", style: "normal" }],
  variable: "--font-general-sans",
});
export const metadata: Metadata = {
  title: "Anirban",
  description: "Generated by create next app",
  icons: "/favicon.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
		<html lang="en">
			<DeviceOverlay />
      <body
        className={`${plusJakartaSans.variable} ${generalSans.variable} antialiased bg-background`}
      >
        <LenisScroll>
          <NavBar />
          <div id="lenis-root">{children}</div>
          <CustomCursor hoverText="See Project" />
          <Footer />
        </LenisScroll>
      </body>
    </html>
  );
}
